
# Regulatory_Interactions
# Columns Names
RI_CYC_ID = 'ECOCYC_ID'
RI_ID = 'REGULATORY_INTERACTION_ID'
TF_CYC_ID = 'TF_ECOCYC_ID'
TF_ID = 'TF_ID'
TF_NAME = 'TF_NAME'
FINAL_STATE = 'FINAL_STATE'
REG_ENTITY_CYC_ID = 'TARGET_ECOCYC_ID'
REG_ENTITY_ID = 'TARGET_ID'
REG_ENTITY_NAME = 'TARGET_NAME'
REG_ENTITY_STRAND = 'TARGET_STRAND'
REG_ENTITY_TYPE = 'TARGET_TYPE'  # (promoter gene or TU)
SITE_CYC_ID = 'SITE_ECOCYC'
SITE_ID = 'SITE_ID'
SITE_LEFT = 'SITE_POSLEFT'
SITE_RIGHT = 'SITE_POSRIGHT'
SITE_LENGTH = 'SITE_LENGTH'
RI_FUNCTION = 'RI_FUNCTION'
RI_DIST_TO_TSS = 'RI_DIST_TO_TSS'
RI_DIST_FIRST_GENE = 'RI_DIST_FIRST_GENE'
RI_FIRST_GENE_ID = 'RI_FIRST_GENE_ID'
RI_ORIENTATION = 'RI_ORIENTATION'
RI_SEQUENCE = 'RI_SEQUENCE'

'''
RI_CYC_ID = 'ECOCYC_ID'
RI_ID = 'RI_ID'
TF_NAME = 'TF_NAME'
FINAL_STATE = 'FINAL_STATE'
REG_ENTITY_NAME = 'PROMOTER/GENE/TU_NAME'
REG_ENTITY_STRAND = 'PROMOTER/GENE/TU_STRAND'
REG_ENTITY_TYPE = 'TARGET_TYPE'  # (promoter gene or TU)
SITE_CYC_ID = 'ECOCYC_SITE_ID'
SITE_ID = 'SITE_ID'
SITE_LEFT = 'SITE_LEFT'
SITE_RIGHT = 'SITE_RIGHT'
SITE_LENGTH = 'SITE_LENGTH'
RI_FUNCTION = 'RI_FUNCT'
RI_DIST_TO_TSS = 'RI_DIST_TO_TSS'
RI_DIST_FIRST_GENE = 'RI_DIST_FIRST_GENE'
RI_FIRST_GENE_ID = 'RI_FIRST_GENE_ID'
RI_ORIENTATION = 'RI_ORIENTATION'
RI_SEQUENCE = 'RI_SEQUENCE'
'''

RI_FIELDS = [
    RI_CYC_ID,
    RI_ID,
    TF_CYC_ID,
    TF_ID,
    TF_NAME,
    FINAL_STATE,
    REG_ENTITY_CYC_ID,
    REG_ENTITY_ID,
    REG_ENTITY_NAME,
    REG_ENTITY_STRAND,
    REG_ENTITY_TYPE,
    SITE_CYC_ID,
    SITE_ID,
    SITE_LEFT,
    SITE_RIGHT,
    SITE_LENGTH,
    RI_FUNCTION,
    RI_DIST_TO_TSS,
    RI_DIST_FIRST_GENE,
    RI_FIRST_GENE_ID,
    RI_ORIENTATION,
    RI_SEQUENCE,
]
# Database Keys
